version: 2.1
jobs:
  build:
      docker:
        # - image: mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview6-disco
        - image: mcr.microsoft.com/dotnet/core/sdk:2.2
      steps: 
        - checkout
        - run:
            name: Restore packages
            command: 
              dotnet restore
        - run:
            name: Build projects
            command: 
              dotnet build -c Release
        - persist_to_workspace:
                  # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
                  # taken to be the root directory of the workspace.
                  root: src
                  # Must be relative path from root
                  paths:
                    - PocketCqrs
  deploy:
      docker:
        # - image: mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview6-disco
        - image: mcr.microsoft.com/dotnet/core/sdk:2.2
      steps: 
        - attach_workspace:
                  at: /PocketCqrs
        - run:
            name: Debug directory
            command:
              ls
        - run:
            name: Pack project
            command:
              dotnet pack --no-build /p:PackageVersion=${CIRCLE_TAG} -o nuget
        - run:
            name: Publish package to nuget
            command:
              dotnet nuget push nuget/PocketCqrs.${CIRCLE_TAG}.nupkg -k ${nugetorgapikey} -s https://api.nuget.org/v3/index.json


workflows:
  build-andpush:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              only: master
          requires:
            - build
