version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview6-disco
    steps: 
      - checkout
      - run:
          name: Restore packages
          command: 
            dotnet restore
      - run:
          name: Build projects
          command: 
            dotnet build
      - run:
          name: Pack project
          command:
            dotnet pack
      - run:
          name: Publish package to nuget
          command:
            dotnet nuget push src/CQRS/bin/Debug/Kofoed.CQRS.0.0.1.nupkg -k ${nugetorgapikey} -s https://api.nuget.org/v3/index.json
